schema_version: v1.0.0
deployment:
    name: VoteResultDeployment
    description: Vote result Service Deployment
    deploymentConfig:
        artifact:
            id: 3e9f0abf-c768-499d-8c46-23455622dc
            containerImage:
                reference: latest
        template:
            moduleRefId: azure:basic-aks-module@1
            inputs:
                cluster: $(cluster)
                pool_name: Azure-Agents
                ports:
                    - containerPort: 80
                      healthCheck: /health
                      name: vote
                      protocol": TCP
                resourceGroup: $(resourceGroup)
        env:
            PG_HOST: ${terraform.db_instance_address.value}
            PG_PASSWORD: ${terraform.postgres_password.value}
            PG_USERNAME: ${terraform.postgres_user.value}
            REDIS_HOST: ${terraform.redis_hostname.value}
            cluster: ${terraform.aks_name.value}
            resourceGroup: ${terraform.aks_rg.value}
        summary:
            - name: Service URL
              command: sleep 60 ; echo http://$(kubectl get svc -n votingresult -o=jsonpath={.items[*].status.loadBalancer.ingress[*].ip})
application:
    import: app-votingResult.yaml
environment:
    import: environment-Voting-Demo.yaml
